.NET 5 and Win-64-FNA Port (#1086)
* Game opens

* Remove XnaContentSource to reduce patch size

* Fix LogArchiver exception spam

* Core assembly unloading

* ModCompile updates

* Update UICreateMod.cs

* (WIP) Moving everythng to terraria step, aiming for universal builds.

* Ported to 64bit FNA

* ModCompile updates

* TerrariaNetCore builds and runs

* NetCore project is now completely cross platform

* Normal project works now too

* Ported to .NET Core

* patch weirdness 1

* patch weirdness 2

* shorten msbuild by like 1 nanosecond

* Merge fix

* yet another patch fix..

* Mir review ack

Need to make NetCore run on x64 next

* Run 64-bit .NET Core 3.1 on vanilla 1.4

WeGame support needed; using RailSDK.NET will crash (BadImageFormatException).

* XNA/32bit/Framework and FNA/64bit/Core compile side-by-side

* tmod patch success

* patcher ignoring my files grrr

* patcher ignoring my files grrr part 2

* use spaces, thanks

* legacy tModLoader runs

* new tModLoader runs

* Made RailSDK AnyCPU and removed its duplicates.

* Reorganized all libraries.

* Fixed .net framework error messages.

* Moving steam_appid around, touching csprojs

* Removed nullable references feature from default mod csproj, until further discussion.

* ModCompile updates

* Legacy ModCompile and new ModCompile.Core

* Readded the 'Debug' suffix to output binaries' names.

* Fixed build errors

* PR review part 1

* PR review part 2

* Update CoreSocialModule patch context

* small patch fix

* Build TerrariaNetCore without any WindowsDesktop references

* Add libmojoshader for linux builds

* Restore wmav2 wavebank support via ffmpeg. Thanks Dradon and Rartrin

* Terraria stage patch cleanup/minimisation

* Remove EffectivePlatform

* Add SDL2 backed MessageBox shim for .NETCore

* cleanup MacOS native libs path

* Fix netframework compile errors

* Fix more netframework compile errors from the 1.4 merge

* Added cross-platform UPnP support for dedicated servers.

* Fixed patching issues from resolving merge conflicts

* Fixed compilation errors from .NET 5

* Fixed ResetStaticMembers doing nothing on .net core.

* Rediffed. Reset your timestamps frequently.

* Shortened a line.

* Fix missing null check on TypeInitializer.Invoke in netframework

* Swap TerrariaNetCore and Terraria_LegacyNetFramework so .NET Core is the default

* Simplify ModCompile and AssemblyManager for .NET Core

* Remove ModCompile folder and UIDeveloperModeHelp

* Fix patching for _LegacyNetFramework

Now correctly uses decompiled to create Legacy versions of files.

* Part 1: Create new patch for config targets

Uses the legacy patches.

* Fixing targets part 1-8 of 2

* Update CaptureCamera to only save if client

SLD2 PNG saving isn't used in NetCore version.

* Swap from system.drawing to ImageSharp in PngReader

* Update ExampleMod.csproj to support SymLink setups

* Fix tModLoader patches due to netcore image save load changes.

* Partial Progress on Fixing ModCompile

Includes splitting the problematic references from the non-problematic.
Note the text file summarizing the references of the two groups; remove before merging.

* Updated ModCompile.cs to have whitelisted filtering by default.

* Fixed mods to build; still getting an error on consecutive builds while mod is loaded.

* Cleanup ModCompile.cs to remove superflous code from fixes.

* Remove System.Drawing dependency, cleanup ModCompile, finish dynamic ExampleMod.csproj

* Fix CaptureCameraPatch, Correct colours in ImageIO

* Remove contentious lines

Re-instate ExampleMod.Sln error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Project "D:\Other\references \tModLoader.targets" was not imported by "D:\Other\tModLoader\ExampleMod\ExampleMod.csproj" at (6,3), due to the file not existing.	ExampleMod	D:\Other\references \tModLoader.targets

* Remove an extra space that I missed

Re: cleanup examplenod.csproj

* Fix Patreon Link and UIMemoryBar

* Move NuGet packages to be in Libraries/NuGet/

Did per: https://stackoverflow.com/questions/55946010/how-to-specify-output-folder-for-the-referenced-nuget-packages

* Add drawing Help Advice Link to ModSources

Added per TODOs.

May need some aesthetic cleanup, and the Github Wiki should probably be updated to have all resources intended.

* Fix a few stray oddities in Main.SetDisplayMode

Fix screenBorderless to not always be true.
Move flag2 to be calculated at the end.
Change num3, num4 to be viewport value specifically in graphics.IsFullScreen
And re-enable graphics.ApplyChanges running within the existing if condition, and not doubling down on ifs.

* Fix UIModItem.Initialize errors

Swap from calling Texture2D.FromStream which was flaking out to use the known working Relogic.Content.PngReader.FromStream

* Remove && false in ModCompile and temp comment out GoG Verifier

* Update .csproj to move most stuff in to Libraries folder

Only thing that isn't moved is the .json's

* Updated & fixed monomod (60b1c7a)

* Removed an unneeded conditional.

* Setup: Removed the SetupDebugging task and its button.

* Deleted the RoslynWrapper directory.

* Oops, leftovers of the previous commit.

* Part 1 of Setting up for eliminating Ref and .dev.json files in folder

Have to use publish on Netcore for 'final release' moving forward.

* Update Terraria.csproj for hiding libs

Build will produce dev.json, but you can change the file paths in it to "Libraries" and it will run fine.
Some code for publish as well, although additionalProbingPaths don't seem to work in the regular runtimeconfig so commented out

* Terraria patches

* Address setup issues 1 of 2

FAILURE: @@ -36567,14 +37135,20 @@

* Update Main.cs.patch

 to have the skip achievements stuff

* Finish bringing Netcore in to the 1.4.2.x age

* Re-organization and updating bat files. Missing Steam?

Now creates the full release zip, less Steam

* Show patch reviewer if fuzzy mode is enabled and there are any failed patches.

* Update patches to Terraria 1.4.2.1

* FIx removed_files.list

* Add missing /Libraries/Common/ files.

* Revert "FIx removed_files.list"

This reverts commit 202ff5b5eb631e12569976921039d732c42c6e81.

* Fix command line mod building

* Add graphics ApplyChanges verbose Logging

* Fix display flickering, and approximately nothing else.

* Death of the embedded dlls! ModCompile surely broken.

* MonoMod (and thus Mono) is now a PackageReference

* produce xml documentation files for net core builds

* Fix Terraria_LegacyNetFramework.sln

* Restore VS mod building with the new Libraries folder. Removed "references" folder

* Cleanup ModCompile and restore ingame mod building. Better compile/package separation now

* Update tmodloader terraria.csproj

- Now places TerrariaHooks.dll in Libraries folder and deps.json, but doesn't use it at compile time.
- Some minor indentation fixes
- Remove unnecessary ItemDefinitionGroup
- Move cleanup task to above the copy to task in the target for ordering sanity
- Fix BinFiles include to actually include subdirectory files

* Revert "1.4.2.1 Main branch merge conflicts"

* Revert "Revert "1.4.2.1 Main branch merge conflicts""

This reverts commit b560af98c9e6ab704abb8340f73288565f16f1dd.

* Fix InstallVerifier for OSX

* Fix missing 'using' in UIModItem.Initialize()

Stream for getting icon.png is now properly temporary

* Return robocopy libraries purge to after copy, should only delete old files.

* Fix asset requesting deadlocks on FNA. GLCallLocker is back!

* Update install Verifier SteamAPI paths and CaptureCamera to not use Texture2D.SaveAsPNG

* De-update InstallVerifier

Creating too many issues.
Need to fundamentally change how steam is detected and ran with all dlls being included automagically

* Fix SteamVerification, Fix Utils.OpenFolder, Minor syntax fixes in csproj

* Netcore Hash Changes

* Finish minor updates coming out of cross-plat testing. Running Linux from Build need testing more

* Fix InstallVerifier + Steam.cs for MacOS terraria installs

* Actually fix InstallVerifier for Mac

* Add additional information comment on why subdirectories are way they are for NuGet

* Part 1: Using Install Scripts to 'install' the portable binaries

1) Shell script untested
2) Batch file tested, need to fix the remove directory command in OLDDIR

* Part 2 of 3: adding auto-fetch for portable runtimes.

Windows is done draft, haven't tested in depth.
Unix is in the works. Current shell file should at least work.

* Update Batch scripts, remove shell scripts until its ready

* Part 3 of 3: Launch and autoinstall scripts.

* Minor cleanup on batch files. No soln for replacing batch files in a non-inflated way

* Move target framework back to Configuration.targets

* Remove redundant patch

* Remove duplicated Main.SetDisplayMode patch

* Revert change to AutoloadAttribute.cs comment

* Misc Install Fixes

- UnloadedTile MP proper fix
- Install Verifier typo for linux
- NuGetPackageID ToLower fix for Linux
- Tweaks on Bat and Shells

* Update CompleteRelease.bat to not include unnecessary 'ref' folder

* Windows Icon fix for launching via "dotnet .dll"

Uses ResourceHacker post install to adjust the portable's exe

* [Needs Review] Update Setup tool to use default dev folder

Updated based on: https://github.com/tModLoader/tModLoader/commit/b1d74a491b88c9dc7c339213616c0dcfb0499e28#diff-8fb6d5f37e8055ce720bd0b1d56587f88c0071f285966ba17e72b2b12672aa73

Also archive the content folder, since hadn't done that yet.

Settings decided to flip about, not sure why, not sure I want to know why.

* Create tModLoader.ico in Libraries/Native so can use it in post-deployment

* Server build elimination

* Cleanup patches where can early return/continue

* Update launchSettings.json to run dotnet tModLoader.dll

* Also fix some bugs with the update csproj button in mod sources

* Disable AppHost generation.

* Fix old patch with Main.Update exception wrapping

* Add hiding Windows Console, fix Icon setting in InstallNetFramework.bat

* Update launchSettings.json.patch

Fix the error with spaces in command Line arg for dotnet.exe

* Terraria.sln Server Build Commit.

* Revert "Cleanup patches where can early return/continue"

This reverts commit 298b3b025a29f66cd0a11d96def5fe8029ae3379.

* Revert "Server build elimination"

This reverts commit d224ede7b9cdd731d19d2820311d1bf6c91933a0.

* Patch Conflicts Fix

* Fix and complete tModLoader.sln patching

* Update batch files regarding server

* Update Program.cs.patch

* Fix bad merge patches. All patch lines are correct again.

* Minor bug fixes to Multiplayer FileName and Hiding the console

I really should have tested before notifying others :pensive:

* Remove AssemblyName config matching and Update ModCompile.cs for server change

* Shell script updates

* Fixing TerrariaHooks.dll onNET5

Updated HookGenTask to actually work, Updated TerrariaHooks.dll

* Fixed HookGen failing to resolve libraries and still using XnaToFna

* Fully removed XnaToFna, updated HookGen nuget.

(cherry picked from commit fbb5c9696b21c1d30cf5a3e8d4b9e9f5881bc84b)

* Mysterious rediff after exact patching worked perfectly fine.

* HookGen.

* Move tModLoader.png to be output from ReleaseExtras

Its only planned use for setting Unix icon at end-deployment, and is tossing weird errors in Build, so pull it out of Libraries\Native output folder and put it in ReleaseExtras.

* Fix TerrariaHooks Reference Assembly Folder setting

* Fix debugging from ExampleMod post Server build change

* Update ModCompile.cs

* Removed the requirement for mod classes names to match internal mod names.

* TEMP Commit - ExampleLuckPlayer HookGen issue

* Cleanup the temp commit, and test more permutations.

* Updated MonoMod to fix reloading issues.

* Delete IL Player Temp, and add outputting scripts to bin

Should have been on a separate branch anyway; Reverses the TEMP commit

Scripts are now output to bin before copying to output dir. Ref folder deletion, steam file releaseExtras couldn't quite get working at the post build; completeRelease.bat remains best for now.

Co-authored-by: Mirsario <me@mirsar.io>
Co-authored-by: Rartrin <polliwhirl@gmail.com>
Co-authored-by: Chicken-Bones <mehvids@gmail.com>
Co-authored-by: nmoll <nmoll@NMOLLER-DESK>
Co-authored-by: Solxanich <59670736+Solxanich@users.noreply.github.com>